### ISSUE TITLE
HList errors

### ISSUE THREAD

**Issue by jimstutt** [mikeizbicki/HLearn#54]
HList.hs 118:5
  'typeOf' is not a (visible) method of class Typeable
HList.hs 288:1
  Kind variable is also used as a type variable: 'a'
  In the declaration for type family: $

ghc-7.8.4 
x86_64
cabal-1.22.2.0
nixos-14.12

**Comment by mikeizbicki** [comment]
It looks like you were trying to use the version on hackage?  That version requires ghc 7.6 and is no longer supported.

**Comment by jimstutt** [comment]
Sorry for the delay in answering. I got the error msg from theHLearn github clone. I've recloned today and no longer have the error so I've closed the issue.
