### ISSUE TITLE
Is HLearn intentionally kept of hackage / stackage?

### ISSUE THREAD

**Issue by paulkoerbitz** [mikeizbicki/HLearn#73]
I am interested in using HLearn in a Haskell command line tool, but having it not available on hackage / stackage (unless I am mistaken) complicates this a bit. Is this intentional and likely to stay this way?

**Comment by mikeizbicki** [comment]
Yes, this is intentional.  HLearn is still experimenting a LOT with the API.  I don't consider it stable enough for a hackage release at this point.

**Comment by paulkoerbitz** [comment]
OK, I understand. Thanks for the prompt reply.
