### ISSUE TITLE
Example of using cover tree?

### ISSUE THREAD

**Issue by tbenst** [mikeizbicki/HLearn#86]
Thanks for making this awesome library available!

I'm relatively new to haskell and slowly working through your code. Do you have an example you can share on how to use the Cover Tree for nearest neighbor? I wasn't able to find it in the Benchmark folder. No worries if it's not documented--any example code would be of help.

Cheers!

**Comment by mikeizbicki** [comment]
Here's a command line interface for doing nearest neighbor queries with the
cover tree:
https://github.com/mikeizbicki/HLearn/blob/master/executables/hlearn-allknn/Main.hs
