### ISSUE TITLE
Interested in contributing

### ISSUE THREAD

**Issue by lachrimae** [mikeizbicki/HLearn#91]
Hi, I'm looking to contribute to Haskell open-source and I have interests and education relevant to data science. Is there missing functionality in HLearn that needs to be implemented?

**Comment by mikeizbicki** [comment]
Unfortunately, HLearn is not currently being used/maintained, so no.  You might look into the data haskell group (https://github.com/DataHaskell), but I'm not sure how active they are right now.

**Comment by lachrimae** [comment]
Good to know, thank you.

Curran McConnell

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
